### ISSUE TITLE
Zobrazovat jen schválená místa

### ISSUE THREAD

**Issue by ares** [AnnaAurinko/bezlepci#3]
Ahoj,

na RG jsme se krátce bavili o tom, že by bylo dobré přidat nějakou frontu na schvalování nových míst, aby se zobrazovala jen ta, která budou schválená adminem. Navrhoval bych následující postup.

K místu bych přidal flag (boolean sloupec), který bude označovat, zda je místo schváleno. Potom bych v modelu Place přidal dva scopy, které budou filtrovat pouze schválená a neschválená místa. Nápovědu a vysvětlení, co je to scope najdete třeba tady http://apidock.com/rails/ActiveRecord/Scoping/Named/ClassMethods/scope

V administraci bude potřeba přidat stránku, která bude zobrazovat všechny dosud neschválená místa (kontrolér je dohledá právě pomocí scope) a v existujícím https://github.com/AnnaAurinko/bezlepci/blob/master/app/controllers/places_controller.rb#L8 se budou naopak zobrazovat jen schválené (stači opět použít dříve definovaný scope)

Pokud by něco nebylo jasné, nebo bych měl něco lépe vysvětlit, nebo zkusit třeba nějakou menší část udělat, aby vás to inspirovalo, tak se ozvěte :-)

**Comment by shosanna** [comment]
Ahoj! Super diky moc za napad a navod, hned jak budu mit cas tak se na to vrhnu, to zni jednoduse :) Dam vedet postup, je fajn ze nekdo sleduje nasi praci a fandi nam ... :)
